#List all airports
SELECT * FROM airports;

#Find airports in a specific country
SELECT name, city FROM airports WHERE country = 'United states of america';

#Count how many airports are in each country
SELECT country, COUNT(*) AS total_airports
FROM airports
GROUP BY country
ORDER BY total_airports DESC;

#List all flights between two airports
SELECT flight_no, departure_time, arrival_time
FROM flights
WHERE origin_airport_id = 1 and destination_airport_id = 2;

#Count number of passengers per flight 
SELECT flight_id, count(*) AS Number_of_Passengers
FROM flights
GROUP BY flight_id;

# Find Busiest airport Most flights departing
SELECT a.name, count(f.flight_id) as total_flights   
FROM flights f
JOIN airports a ON f.origin_airport_id = a.airport_id
GROUP BY a.name
ORDER BY total_flights DESC;

# Employees working at each airport
SELECT a.name, e.role, count(*) AS total_employee
FROM employees e
JOIN airports a ON e.base_airport_id = a.airport_id
GROUP BY a.name, e.role;

# Revenue Generated by Each Airport
SELECT a.name AS airports, SUM(t.price_usd) AS Total_Revenue
FROM tickets t
JOIN flights f on t.flight_id = f.flight_id
JOIN airports a ON f.origin_airport_id = a.airport_id
GROUP BY a.name
ORDER BY Total_Revenue;

# Top 10 Passengers by Spending
SELECT 
    p.passenger_id, 
    p.first_name, 
    p.last_name, 
    SUM(t.price_usd) AS total_spend
FROM passengers p
JOIN tickets t ON p.passenger_id = t.passenger_id
GROUP BY p.passenger_id, p.first_name, p.last_name
ORDER BY total_spend DESC
LIMIT 10;

# Flight Delay MOnitoring
SELECT f.flight_no, a1.name AS Origin, a2.name AS Destination, f.status
FROM flights f
JOIN airports a1 ON f.origin_airport_id = a1.airport_id
JOIN airports a2 ON f.destination_airport_id = a2.airport_id
WHERE f.status = 'Delayed';

# Employee Distribution by role
SELECT a.name AS airport, e.role, COUNT(*) AS total_employees
FROM employees e
JOIN airports a ON e.base_airport_id = a.airport_id
GROUP BY a.name, e.role
ORDER BY a.name;

# Passenger Travel History
SELECT p.first_name, p.last_name, f.flight_no, a1.name AS origin, a2.name AS destination, t.booking_date
FROM passengers p
JOIN tickets t ON p.passenger_id = t.passenger_id
JOIN flights f ON t.flight_id = f.flight_id
JOIN airports a1 ON f.origin_airport_id = a1.airport_id
JOIN airports a2 ON f.destination_airport_id = a2.airport_id
WHERE p.passenger_id = 209; 











